language: csharp
solution: RestWell.sln
dist: trusty
mono: none
dotnet: 2.0.0
install:
  - dotnet restore
script:
  - dotnet test RestWell.Test/RestWell.Test.csproj -p:CollectCoverage=true
notifications:
  email: false
