language: csharp
solution: RestWell.sln
dist: trusty
mono: none
dotnet: 2.1.300
install:
  - dotnet restore
script:
  - dotnet test RestWell.Test/RestWell.Test.csproj -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:Exclude="[RestWell.Test*]*"
  - curl -s https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f ./SLOBSharp.Tests/coverage.opencover.xml
notifications:
  email: false
